name: "Build & Check"


on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      - 'CODE_OF_CONDUCT.md'
      - './fastlane/**'
      
    branches: main
    
jobs:
    build:
        name: Build & Check
        runs-on: windows-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup-Java
              uses: actions/setup-java@v3.12.0
              with:
                distribution: 'oracle'
                java-version: '17'

            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                flutter-version: '3.24.0'
                channel: 'stable'

            - name: Install Dependencies
              run: flutter pub get
            
            - name: Build App files
              run: flutter build apk --release --build-number ${{github.run_number}}


            - name: Rename APK file
              run: Rename-Item -Path "build/app/outputs/flutter-apk/app-release.apk" -NewName "bloomee_tunes_android_v2.11.6+${{github.run_number}}.apk"

            - name: Build Windows App
              run: flutter build windows --release --build-number ${{github.run_number}}

            - name: Rename file
              run: Rename-Item -Path "build/windows/x64/runner/Release/bloomee.exe" -NewName "Bloomee.exe"
           
            - name: ZIP build
              run: Compress-Archive -Path build/windows/x64/runner/Release/* -Destination  build/windows/x64/bloomee_tunes_windows_x64_v2.11.6+${{github.run_number}}.zip
            
            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                name: Release
                path: |
                  build/app/outputs/flutter-apk/bloomee_tunes_android_v2.11.6+${{github.run_number}}.apk
                  build/windows/x64/bloomee_tunes_windows_x64_v2.11.6+${{github.run_number}}.zip


    